keep_words:
  - not
  - "no"
  - "couldn't"
  - "can't"
  - "won't"
  - "wouldn't"
  - "shouldn't"
  - "doesn't"
  - "didn't"
  - "isn't"
  - "aren't"
  - "wasn't"
  - "haven't"
  - "hasn't"
  - "hadn't"
  - "don't"
  - "didn'"
  - "needn't"
  - "needn'"
  - "mustn't"
  - "mightn't"
  - "shan't"
  - "wouldn"
  - "don'"
  - "wasn'"
  - against
  - nor
  - but
  - however
  - although
  - though
  - yet
  - unless
  - very
  - so
  - really
  - just
  - too
  - still
  - barely
  - hardly
  - almost
  - absolutely
  - completely
  - totally
  - definitely
  - certainly
  - slightly
  - strongly
  - somewhat
  - extremely

